[project]
name = "python-and-hpc"
version = "0.1.0"
description = "UV port of 02613 Fast Python and HPC course environment"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "asciitree==0.3.3",
    "blosc==1.11.4",
    "contourpy==1.3.3",
    "cupy-cuda12x==13.6.0; sys_platform == 'linux' and platform_machine == 'x86_64'",
    "cycler==0.12.1",
    "deprecated==1.3.1",
    "donfig==0.8.1.post1",
    "fasteners==0.19",
    "fastrlock==0.8.3",
    "fonttools==4.62.0",
    "google-crc32c==1.8.0",
    "kiwisolver==1.5.0",
    "line-profiler==5.0.2",
    "llvmlite==0.46.0",
    "matplotlib==3.10.8",
    "msgpack==1.1.2",
    "munkres==1.1.4",
    "numba==0.63.1",
    "numcodecs==0.15.1",
    "numpy==1.26.4",
    "packaging==26.0",
    "pandas==3.0.2",
    "pillow==12.1.1",
    "pyarrow==23.0.1",
    "pyparsing==3.3.2",
    "python-dateutil==2.9.0.post0",
    "pyyaml==6.0.3",
    "setuptools==82.0.1",
    "six==1.17.0",
    "typing-extensions==4.15.0",
    "tzdata>=2025.1",
    "wheel==0.46.3",
    "wrapt==2.1.2",
    "zarr==2.18.7",
]
